permalink: /:year/:month/:day/:title.html
paginate: 50
markdown: kramdown

kramdown:
  input: GFM

# 作者信息
author:
  name: Drew
  email: drewz.lin@gmail.com
  #link: http://blog.csdn.net/ekeuy
  Twitter: https://twitter.com/dleyanlin
  github: https://github.com/dleyanlin

# 站点信息
title: Blog
description: Recording Place
url: http://dleyanlin.github.io
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-56952211-1
  url: zmywly8866.github.io

# disqus 设置
disqus:
  shortname: dleyanlin

# 主题设置，自动激活某个标签
active: 技术

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
  content: 目录
